config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/charts/realtime/')),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    # url(r'^users/', include('kchart.users.urls', namespace='users')),
    # url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^api/v1/', include('kchart.api.urls', namespace='api-v1')),
    url(r'^charts/', include('kchart.charts.urls', namespace='charts')),
    url(r'^songs/', include('kchart.songs.urls', namespace='songs')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

kchart/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from .views import (
    AggregateHourlySongChartViewSet,
    HourlySongChartViewSet,
    SongViewSet,
)


aggregate_hourly_song_chart_detail = AggregateHourlySongChartViewSet.as_view({'get': 'retrieve'})
hourly_song_chart_detail = HourlySongChartViewSet.as_view({'get': 'retrieve'})
song_detail = SongViewSet.as_view({'get': 'retrieve'})

urlpatterns = [
    url(r'^charts/realtime/$', aggregate_hourly_song_chart_detail, name='realtime'),
    url(r'^charts/realtime/(?P<slug>.+)/$', hourly_song_chart_detail, name='realtime-service'),
    url(r'^songs/(?P<pk>\d+)/$', song_detail, name='song-detail'),
]

kchart/charts/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/charts/realtime/')),
    url(
        regex=r'^realtime/$',
        view=views.HourlySongChartView.as_view(),
        name='hourly-chart-detail'
    ),
    url(
        regex=r'^stats/$',
        view=views.StatsView.as_view(),
        name='chart-stats'
    ),
]

kchart/songs/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.SongView.as_view(),
        name='song-detail'
    ),
]

kchart/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

kchart/charts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from datetime import timedelta
import pickle

from django.core.cache import cache
from django.db import models
from django.db.models import (
    ExpressionWrapper,
    F,
    Min,
    Sum,
)
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _

from .utils import utcnow, strip_to_hour, KR_TZ


class Artist(models.Model):

    name = models.CharField(_('Artist name'), blank=True, max_length=255)
    debut_date = models.DateField(_('Artist debut date'), null=True)

    def __str__(self):
        return self.name


class Album(models.Model):

    name = models.CharField(_('Album name'), blank=True, max_length=255)
    artists = models.ManyToManyField(Artist, related_name='albums')
    release_date = models.DateField(_('Album release date'))

    def __str__(self):
        artist_names = []
        for artist in self.artists.all():
            artist_names.append(str(artist))
        return '{} - {}'.format(', '.join(artist_names), self.name)


class Song(models.Model):

    name = models.CharField(_('Song name'), blank=True, max_length=255)
    artists = models.ManyToManyField(Artist, related_name='songs')
    album = models.ForeignKey(Album, on_delete=models.PROTECT, related_name='songs')
    release_date = models.DateField(_('Song release date'))

    def __str__(self):
        return '{} - {}'.format(self.artist_names, self.name)

    @property
    def artist_names(self):
        artists = self.artists.all()
        if len(artists) <= 2:
            sep = ' & '
        else:
            sep = ', '
        return sep.join(str(artist) for artist in artists)

    def get_peak_realtime_position(self, service=None):
        if service:
            q = HourlySongChartEntry.objects.filter(hourly_chart__chart__service=service)
        else:
            q = AggregateHourlySongChartEntry.objects
        q = q.filter(song=self, position__lte=100)
        position = q.aggregate(Min('position'))['position__min']
        if position:
            timestamp = q.filter(position=position).aggregate(
                Min('hourly_chart__hour')
            )['hourly_chart__hour__min']
            return (position, timestamp)
        else:
            raise Song.HasNotCharted()

    def get_current_realtime_position(self, service=None):
        if service:
            q = HourlySongChartEntry.objects.filter(hourly_chart__chart__service=service)
        else:
            q = AggregateHourlySongChartEntry.objects
        try:
            entry = q.get(song=self, hourly_chart__hour=strip_to_hour(utcnow()))
            if entry.position > 100:
                return None
            else:
                return entry.position
        except ObjectDoesNotExist:
            return None

    def get_initial_realtime_position(self, service=None):
        if service:
            q = HourlySongChartEntry.objects.filter(hourly_chart__chart__service=service)
        else:
            q = AggregateHourlySongChartEntry.objects
        try:
            entry = q.filter(song=self, position__lte=100).earliest('hourly_chart__hour')
            return (entry.position, entry.hourly_chart.hour)
        except ObjectDoesNotExist:
            raise Song.HasNotCharted()

    def get_final_realtime_position(self, service=None):
        if service:
            q = HourlySongChartEntry.objects.filter(hourly_chart__chart__service=service)
        else:
            q = AggregateHourlySongChartEntry.objects
        try:
            entry = q.filter(song=self, position__lte=100).latest('hourly_chart__hour')
            return (entry.position, entry.hourly_chart.hour)
        except ObjectDoesNotExist:
            raise Song.HasNotCharted()

    def get_realtime_details(self, service=None):
        try:
            details = {'has_charted': True}
            (initial_position, initial_timestamp) = self.get_initial_realtime_position(service)
            (peak_position, peak_timestamp) = self.get_peak_realtime_position(service)
            current_position = self.get_current_realtime_position(service)
            details['initial_position'] = initial_position
            details['initial_timestamp'] = initial_timestamp
            details['peak_position'] = peak_position
            details['peak_timestamp'] = peak_timestamp
            details['current_position'] = current_position
            if not current_position:
                (final_position, final_timestamp) = self.get_final_realtime_position(service)
                details['final_position'] = final_position
                details['final_timestamp'] = final_timestamp
            return details
        except Song.HasNotCharted:
            return {'has_charted': False}

    def get_chart_details(self, include_service_slugs=[]):
        realtime_details = {
            'kchart': self.get_realtime_details(),
        }
        for slug in include_service_slugs:
            try:
                service = MusicService.objects.get(slug=slug)
                realtime_details[slug] = self.get_realtime_details(service)
            except MusicService.DoesNotExist:
                # ignore invalid query params
                pass
        return {'realtime': realtime_details}

    class HasNotCharted(Exception):
        pass


class MusicService(models.Model):
    '''A Korean digital music service'''

    name = models.CharField(_('Music service name'), blank=True, max_length=255)
    url = models.URLField(_('Music service URL'), blank=True)
    _artist_url = models.URLField(_('Base artist URL'), blank=True)
    _album_url = models.URLField(_('Base album URL'), blank=True)
    _song_url = models.URLField(_('Base song URL'), blank=True)
    slug = models.SlugField(_('Slug name'), blank=True)

    def __str__(self):
        return self.name

    def get_artist_url(self, artist_id):
        '''Return the URL for the specified artist page

        :param artist_id: The service-specific artist id
        :rtype: str
        '''
        return self._artist_url.format(artist_id=artist_id)

    def get_album_url(self, album_id):
        '''Return the URL for the specified album page

        :param album_id: The service-specific album id
        :rtype: str
        '''
        return self._album_url.format(album_id=album_id)

    def get_song_url(self, song_id):
        '''Return the URL for the specified album page

        :param album_id: The service-specific album id
        :rtype: str
        '''
        return self._song_url.format(song_id=song_id)


class MusicServiceArtist(models.Model):
    '''Table for mapping Artist ID to a MusicService artist ID'''
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    service = models.ForeignKey(MusicService, on_delete=models.CASCADE)
    service_artist_id = models.IntegerField()

    class Meta:
        unique_together = (('service', 'artist'), ('service', 'service_artist_id'))


class MusicServiceAlbum(models.Model):
    '''Table for mapping Album ID to a MusicService artist ID'''
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    service = models.ForeignKey(MusicService, on_delete=models.CASCADE)
    service_album_id = models.IntegerField()

    class Meta:
        unique_together = (('service', 'album'), ('service', 'service_album_id'))


class MusicServiceSong(models.Model):
    '''Table for mapping Song ID to a MusicService song ID'''
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name='service_songs')
    service = models.ForeignKey(MusicService, on_delete=models.CASCADE)
    service_song_id = models.IntegerField()

    class Meta:
        unique_together = (('service', 'song'), ('service', 'service_song_id'))

    @property
    def url(self):
        return self.service.get_song_url(self.service_song_id)


class UnknownServiceSong(models.Model):
    '''Table for songs that need to be manually added to the db'''
    service = models.ForeignKey(MusicService, on_delete=models.CASCADE)
    service_song_id = models.IntegerField()

    class Meta:
        unique_together = (('service', 'service_song_id'))


class Chart(models.Model):

    service = models.ForeignKey(MusicService, on_delete=models.PROTECT)
    name = models.CharField(_('Chart name'), blank=True, max_length=255)
    url = models.URLField(_('Chart URL'), blank=True)
    weight = models.FloatField(_('Chart aggregation weight'), default=1.0)

    def __str__(self):
        return self.name

    @property
    def slug(self):
        return self.service.slug


class HourlySongChart(models.Model):

    chart = models.ForeignKey(Chart, on_delete=models.CASCADE)
    hour = models.DateTimeField(_('Chart start hour'))

    def __str__(self):
        return '{} <{}>'.format(self.chart.name, self.hour.astimezone(KR_TZ).strftime('%Y.%m.%d-%H'))

    class Meta:
        unique_together = ('chart', 'hour')
        ordering = ['-hour', 'chart']

    def update_next_chart(self):
        try:
            next_chart = HourlySongChart.objects.get(chart=self.chart, hour=self.hour + timedelta(hours=1))
            for entry in next_chart.entries.all():
                entry.update_prev_position()
        except HourlySongChart.DoesNotExist:
            pass


class HourlySongChartBacklog(models.Model):

    chart = models.OneToOneField(Chart, on_delete=models.CASCADE, related_name='hourly_backlog')
    next_backlog_timestamp = models.DateTimeField(
        _('Time from which to start the next backlog operation'),
        auto_now_add=True
    )
    last_modified = models.DateTimeField(auto_now=True)

    def find_next_hour_to_backlog(self):
        hour = strip_to_hour(self.next_backlog_timestamp)
        try:
            while HourlySongChart.objects.get(chart=self.chart, hour=hour):
                hour = hour - timedelta(hours=1)
        except HourlySongChart.DoesNotExist:
            pass

kchart/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

kchart/api/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from datetime import datetime

from rest_framework.exceptions import NotFound
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.viewsets import GenericViewSet

from ..charts.models import (
    AggregateHourlySongChart,
    HourlySongChart,
    MusicService,
    Song
)
from ..charts.serializers import (
    AggregateHourlySongChartSerializer,
    HourlySongChartSerializer,
    SongDetailSerializer,
)
from ..charts.utils import KR_TZ


class HourlySongChartViewSet(RetrieveModelMixin, GenericViewSet):
    '''Viewset for viewing hourly song charts'''

    serializer_class = HourlySongChartSerializer

    def get_object(self):
        q = HourlySongChart.objects
        service = None
        if 'slug' in self.kwargs:
            try:
                service = MusicService.objects.get(slug=self.kwargs['slug'])
                q = q.filter(chart__service=service)
            except MusicService.DoesNotExist:
                raise NotFound('No such music service')
        else:
            raise NotFound('No such music service')
        hour_str = self.request.query_params.get('hour', None)
        if hour_str:
            try:
                hour = KR_TZ.localize(datetime.strptime(hour_str, '%Y%m%d%H'))
            except ValueError:
                raise NotFound('Invalid hour parameter')
        else:
            hour = HourlySongChart.objects.filter(chart__service=service).first().hour
        q = q.filter(hour=hour)
        return q.first()


class AggregateHourlySongChartViewSet(RetrieveModelMixin, GenericViewSet):
    '''Viewset for viewing hourly song charts'''

    serializer_class = AggregateHourlySongChartSerializer
    lookup_field = 'hour'

    def get_object(self):
        q = AggregateHourlySongChart.objects
        hour_str = self.request.query_params.get('hour', None)
        if hour_str:
            try:
                hour = KR_TZ.localize(datetime.strptime(hour_str, '%Y%m%d%H'))
            except ValueError:
                raise NotFound('Invalid hour parameter')
            q = q.filter(hour=hour)
        return q.first()


class SongViewSet(RetrieveModelMixin, GenericViewSet):
    ''' Viewset for songs'''

    serializer_class = SongDetailSerializer

    def get_object(self):
        q = Song.objects.get(pk=int(self.kwargs['pk']))
        return q

    def get_serializer_context(self):
        extra = self.request.query_params.get('extra', None)
        if extra:
            return {'include_service_slugs': extra.split(',')}
        else:
            return {}

kchart/songs/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.views.generic import (
    DetailView,
)

from ..charts.models import (
    Song,
)


class SongView(DetailView):

    template_name = 'songs/song_detail.html'
    model = Song

kchart/templates/charts/hourlysongchart_detail.html
{% extends "base.html" %}
{% load static %}{% load i18n %}{% load charts_tags %}
{% block title %}kchart.io | Realtime Charts{% endblock %}

{% block content %}

<div class="container">
  <div class="dashhead">
    <div class="dashhead-titles">
      <h3 class="dashhead-subtitle">Realtime</h3>
      <h1 class="dashhead-title">Charts</h1>
    </div>

    <div class="dashhead-toolbar">
      <form method="get">
        <div class="input-with-icon dashhead-toolbar-item">
          <input type="text" value="{{ hour|date:'Ymd' }}" class="form-control" data-provide="datepicker" data-date-format="yyyymmdd" name="date">
          <span class="icon icon-calendar"></span>
        </div>
        <div class="dashhead-toolbar-item">
          <select class="form-control custom-select" name="hour">
            {% for i in 24|get_range %}
            <option value="{{ i }}" {% if i == hour.hour %}selected{% endif %}>{{ i|stringformat:"02d" }}:00</option>
            {% endfor %}
          </select>
        </div>
        <div class="btn-group dashhead-toolbar-item">
          <button type="submit" class="btn btn-primary-outline">Go</button>
        </div>
        <span class="dashhead-toolbar-divider hidden-xs"></span>
        <div class="btn-group dashhead-toolbar-item">
          <a class="btn btn-primary-outline" href="{% url 'charts:hourly-chart-detail' %}">Latest</a>
        </div>
      </form>
    </div>
  </div>

  {% if not object %}
  <div>
    <p>No chart data available for this date.</p>
  </div>
  {% else %}
  <div class="hr-divider">
    <ul class="nav nav-pills hr-divider-content hr-divider-nav" role="tablist">
      <li role="presentation" class="active"><a href="#kchart" aria-controls="kchart" role="tab" data-toggle="tab">overall</a></li>
      {% for hourly_chart in object.charts.all %}
      <li role="presentation"><a href="#{{ hourly_chart.chart.service.slug }}" aria-controls="{{ hourly_chart.chart.service.slug }}" role="tab" data-toggle="tab">{{ hourly_chart.chart.service.slug }}</a></li>
      {% endfor %}
    </ul>
  </div>

  <div class="tab-content">
    {% for hourly_chart in object|chart_list %}
    <div role="tabpanel" class="tab-pane{% if forloop.first %} active{% endif %}" id="{% if forloop.first %}kchart{% else %}{{ hourly_chart.chart.service.slug }}{% endif %}">
      <div class="container">
        <div class="dashhead">
          <div class="dashhead-titles">
            <h6 class="dashhead-subtitle">{{ hourly_chart.hour|date:'Y.m.d H' }}:00 KST</h6>
            <h3 class="dashhead-title">{% if forloop.first %}{{ hourly_chart.name }}{% else %}{{ hourly_chart.chart.name }}{% endif %}</h3>
          </div>
        </div>
        <div class="row">
          <table class="table table-hover">
            <thead>
              <tr>
                <td>Rank</td>
                {% if forloop.first %}<td>Score</td>{% endif %}
                <td>Song</td>
                <td>Album</td>
                <td>Artist(s)</td>
              </tr>
            </thead>
            <tbody>
              {% for entry in hourly_chart.entries.all|slice:':100' %}
              <tr>
                <td>
                  {{ entry.position }}
                  {% if not entry.prev_position %}
                  <small class="text-info">New!</span></small>
                  {% elif entry.position < entry.prev_position %}
                  <small class="text-success"><span class="icon icon-arrow-up"></span>{{ entry.prev_position|subtract:entry.position }}</small>
                  {% elif entry.position > entry.prev_position %}
                  <small class="text-danger"><span class="icon icon-arrow-down"></span>{{ entry.position|subtract:entry.prev_position }}</small>
                  {% else %}
                  <small class="text-muted"><span class="icon icon-swap"></span></small>
                  {% endif %}
                </td>
                {% if forloop.parentloop.first %}<td>{{ entry.score|floatformat:4 }}</td>{% endif %}
                <td><a href="{% url 'songs:song-detail' entry.song.pk %}">{{ entry.song.name }}</a></td>
                <td>{{ entry.song.album.name }}</td>
                <td>{% for artist in entry.song.artists.all %}{% if not forloop.first %}, {% endif %}{{ artist.name }}{% endfor %}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

</div>

{% endblock content %}

kchart/templates/charts/hourlysongchart_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}{% load charts_tags %}
{% block title %}kchart.io | Realtime Charts{% endblock %}

{% block content %}

<div class="container">
  <div class="dashhead">
    <div class="dashhead-titles">
      <h3 class="dashhead-subtitle">Realtime</h3>
      <h1 class="dashhead-title">Charts</h1>
    </div>

    <div class="dashhead-toolbar">
      <form method="get">
        <div class="input-with-icon dashhead-toolbar-item">
          <input type="text" value="{{ hour|date:'Ymd' }}" class="form-control" data-provide="datepicker" data-date-format="yyyymmdd" name="date">
          <span class="icon icon-calendar"></span>
        </div>
        <div class="dashhead-toolbar-item">
          <select class="form-control" name="hour">
            {% for i in 24|get_range %}
            <option value="{{ i }}" {% if i == hour.hour %}selected{% endif %}>{{ i|stringformat:"02d" }}:00</option>
            {% endfor %}
          </select>
        </div>
        <div class="btn-group dashhead-toolbar-item">
          <button type="submit" class="btn btn-primary-outline">Go</button>
        </div>
        <span class="dashhead-toolbar-divider hidden-xs"></span>
        <div class="btn-group dashhead-toolbar-item">
          <a class="btn btn-primary-outline" href="{% url 'charts:hourly-chart-list' %}">Latest</a>
        </div>
      </form>
    </div>
  </div>

  {% if not object_list %}
  <div>
    <p>No chart data available for this date.</p>
  </div>
  {% else %}
  <div class="hr-divider">
    <ul class="nav nav-pills hr-divider-content hr-divider-nav" role="tablist">
      <li role="presentation" class="active"><a href="#kchart" aria-controls="kchart" role="tab" data-toggle="tab">overall</a></li>
      {% for chart in object_list|slice:"1:" %}
      <li role="presentation"><a href="#{{ chart.chart.service.slug }}" aria-controls="{{ chart.chart.service.slug }}" role="tab" data-toggle="tab">{{ chart.chart.service.slug }}</a></li>
      {% endfor %}
    </ul>
  </div>

  <div class="tab-content">
    {% for chart in object_list %}
    <div role="tabpanel" class="tab-pane{% if forloop.first %} active{% endif %}" id="{% if forloop.first %}kchart{% else %}{{ chart.chart.service.slug }}{% endif %}">
      <div class="container">
        <div class="dashhead">
          <div class="dashhead-titles">
            <h6 class="dashhead-subtitle">{{ chart.hour|date:'Y.m.d H' }}:00 KST</h6>
            <h3 class="dashhead-title">{% if forloop.first %}{{ chart.name }}{% else %}{{ chart.chart.name }}{% endif %}</h3>
          </div>
        </div>
        <div class="row">
          <table class="table table-hover">
            <thead>
              <tr>
                <td>Rank</td>
                {% if forloop.first %}<td>Score</td>{% endif %}
                <td>Song</td>
                <td>Album</td>
                <td>Artist(s)</td>
              </tr>
            </thead>
            <tbody>
              {% for entry in chart.entries.all|slice:':100' %}
              <tr onclick="input" data-toggle="modal" href="#songModal" data-song-id="{{ entry.song.id }}" data-chart-slug="{% if forloop.parentloop.first %}kchart{% else %}{{ chart.chart.service.slug }}{% endif %}">
                <td>
                  {{ entry.position }}
                  {% if not entry.prev_position %}
                  <small class="text-info">New!</span></small>
                  {% elif entry.position < entry.prev_position %}
                  <small class="text-success"><span class="icon icon-arrow-up"></span>{{ entry.prev_position|subtract:entry.position }}</small>
                  {% elif entry.position > entry.prev_position %}
                  <small class="text-danger"><span class="icon icon-arrow-down"></span>{{ entry.position|subtract:entry.prev_position }}</small>
                  {% else %}
                  <small class="text-muted"><span class="icon icon-swap"></span></small>
                  {% endif %}
                </td>
                {% if forloop.parentloop.first %}<td>{{ entry.score|floatformat:4 }}</td>{% endif %}
                <td>{{ entry.song.name }} </td>
                <td>{{ entry.song.album.name }}</td>
                <td>{% for artist in entry.song.artists.all %}{% if not forloop.first %}, {% endif %}{{ artist.name }}{% endfor %}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

</div>

{% endblock content %}

{% block modal %}
<div class="modal fade" id="songModal" tabindex="-1" role="dialog" aria-labelledby="songModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title" id="songTitle">song title</h3>
      </div>
      <div class="modal-body modal-body-scroller">
        <table class="table">
          <tbody>
            <tr>
              <th scope="row">Album</th>
              <td id="songAlbum"></td>
            </tr>
            <tr>
              <th scope="row">Artist(s)</th>
              <td id="songArtists"></td>
            </tr>
            <tr>
              <th scope="row">Release Date</th>
              <td id="songReleaseDate"></td>
            </tr>
            <tr>
              <th scope="row">Current kchart.io rank</th>
              <td id="songRank"></td>
            </tr>
            <tr>
              <th scope="row">Peak kchart.io rank</th>
              <td id="songPeakRank"></td>
            </tr>
          </tbody>
        </table>
      </div>
  </div>
</div>
{% endblock modal %}

kchart/templates/charts/stats.html
{% extends "base.html" %}
{% block title %}kchart.io | Stats{% endblock %}

{% block content %}
<div class="container">
  <div class="dashhead">
    <div class="dashhead-titles">
      <h1 class="dashhead-title">kchart.io Statistics</h1>
    </div>
  </div>
  <hr />

  <ul>
    <li>Melon data available through {{ melon_earliest|date:'Y.m.d H' }}:00 KST</li>
    <li>Genie data available through {{ genie_earliest|date:'Y.m.d H' }}:00 KST</li>
    <li>Bugs data available through {{ bugs_earliest|date:'Y.m.d H' }}:00 KST</li>
    <li>Mnet data available through {{ mnet_earliest|date:'Y.m.d H' }}:00 KST</li>
    <li>{{ song_count }} charted songs indexed</li>
    <li>{{ artist_count }} charted artists indexed</li>
    <li>{{ album_count }} charted albums indexed</li>
  </ul>
</div>
{% endblock %}